  app:
    build: .
    container_name: solusphere_app
    restart: always
    ports:
      - "2080:2080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Enable AWS Secrets Manager
      - USE_AWS_SECRETS_MANAGER=true
      - USE_SECRETS_AGENT=false
      
      # AWS Configuration
      - AWS_REGION=eu-west-1
      - AWS_SECRET_NAME=solusphere/prod
      - AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY=YOUR_SECRET_KEY
      # Remove or set to false
      - AWS_EC2_METADATA_DISABLED=false
      
      # Database config (as fallback)
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=solusphere_users
      - DB_PASSWORD=Caswell1234
      - DB_NAME=solusphere
      
      # App Configuration
      - GIN_MODE=release
      - PORT=2080
      - UPLOAD_DIR=/app/uploads
      
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network