package services

import (
	"bytes"
	"fmt"
	"strings"

	docx "github.com/fumiama/go-docx"
)

func buildWordReport(content SIAReportContent) ([]byte, error) {
	doc := docx.New().WithDefaultTheme().WithA4Page()

	title := doc.AddParagraph()
	title.AddText(content.Title).Bold().Size("32").Color("4B0082")

	meta := doc.AddParagraph()
	meta.AddText("Generated by SIA (Smart Intelligence Assistant)").Italic().Size("20").Color("666666")

	summaryHeading := doc.AddParagraph()
	summaryHeading.AddText("Executive Summary").Bold().Size("26").Color("0097A7")
	doc.AddParagraph().AddText(content.Summary).Size("22")

	for _, section := range content.Sections {
		if section.Heading != "" {
			heading := doc.AddParagraph()
			heading.AddText(section.Heading).Bold().Size("24").Color("0097A7")
		}
		for _, paragraph := range section.Paragraphs {
			doc.AddParagraph().AddText(paragraph).Size("22")
		}
		for _, bullet := range section.Bullets {
			p := doc.AddParagraph()
			p.AddText("• " + bullet).Size("22")
		}
	}

	for _, table := range content.Tables {
		if table.Title != "" {
			doc.AddParagraph().AddText(table.Title).Bold().Size("22")
		}
		if len(table.Headers) == 0 {
			continue
		}
		rowCount := len(table.Rows) + 1
		t := doc.AddTable(rowCount, len(table.Headers), 9000, nil)
		for col, header := range table.Headers {
			cell := t.TableRows[0].TableCells[col]
			cell.AddParagraph().AddText(header).Bold().Size("20")
		}
		for rowIdx, row := range table.Rows {
			for colIdx, header := range table.Headers {
				value := ""
				if colIdx < len(row) {
					value = row[colIdx]
				}
				cell := t.TableRows[rowIdx+1].TableCells[colIdx]
				cell.AddParagraph().AddText(value).Size("20")
				_ = header
			}
		}
	}

	if len(content.Recommendations) > 0 {
		doc.AddParagraph().AddText("Recommendations").Bold().Size("24").Color("0097A7")
		for _, item := range content.Recommendations {
			doc.AddParagraph().AddText("• " + item).Size("22")
		}
	}

	if len(content.Sources) > 0 {
		doc.AddParagraph().AddText("Sources").Bold().Size("24").Color("0097A7")
		for _, source := range content.Sources {
			label := sourceLabel(source)
			if source.URL != "" {
				doc.AddParagraph().AddLink(label, source.URL)
			} else {
				doc.AddParagraph().AddText(label).Size("20")
			}
		}
	}

	var buf bytes.Buffer
	if _, err := doc.WriteTo(&buf); err != nil {
		return nil, fmt.Errorf("write docx: %w", err)
	}
	return buf.Bytes(), nil
}

func sourceLabel(source SIAReportSource) string {
	if source.Title != "" && source.URL != "" {
		return fmt.Sprintf("%s (%s)", source.Title, source.URL)
	}
	if source.Title != "" {
		return source.Title
	}
	return strings.TrimSpace(source.URL)
}
