package services

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"solusphere_backend/internal/ai"
)

const siaReportJSONPrompt = `You are SIA (Smart Intelligence Assistant), Solusphere's research and reporting agent.
Research the user's topic thoroughly. When web search is available, use multiple independent credible sources.
Return ONLY valid JSON (no markdown fences, no commentary) matching this schema:
{
  "title": "short report title",
  "summary": "executive summary paragraph",
  "sections": [
    {
      "heading": "section heading",
      "paragraphs": ["paragraph text"],
      "bullets": ["bullet point"]
    }
  ],
  "tables": [
    {
      "title": "optional table title",
      "headers": ["column1", "column2"],
      "rows": [["value1", "value2"]]
    }
  ],
  "recommendations": ["actionable recommendation"],
  "sources": [{"title": "source title", "url": "https://..."}]
}
Rules:
- Provide at least 3 sections for substantive research topics when possible.
- Include tables when comparisons, metrics, or structured facts help the reader.
- Include at least 3 sources when credible sources are available; otherwise include all available sources and keep claims cautious.
- Do not invent URLs or statistics.`

// GenerateSIAReport researches the prompt and returns a Word, Excel, or PowerPoint file.
func GenerateSIAReport(prompt string, format ReportFormat, webSearch bool) (*GeneratedReport, error) {
	if !IsOpenAIInitialized() {
		return nil, fmt.Errorf("OpenAI is not configured")
	}

	prompt = strings.TrimSpace(prompt)
	if prompt == "" {
		return nil, fmt.Errorf("prompt cannot be empty")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	result, err := ai.GenerateTextResultWithDefault(ctx, ai.GenerateTextRequest{
		SystemPrompt: siaReportJSONPrompt,
		UserPrompt: fmt.Sprintf(
			"Create a research report for export as %s.\nUser request:\n%s",
			format.Extension(),
			prompt,
		),
		MaxOutputTokens: 3500,
		Temperature:     0.2,
		WebSearch:       webSearch,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to generate report content: %w", err)
	}

	content, err := parseReportJSON(result.Text)
	if err != nil {
		return nil, fmt.Errorf("failed to parse report content: %w", err)
	}
	normalizeReportContent(&content)
	mergeSources(&content, result.Citations)

	data, err := buildReportFile(content, format)
	if err != nil {
		return nil, fmt.Errorf("failed to build %s report: %w", format, err)
	}

	filename := sanitizeFilenamePart(content.Title) + "." + format.Extension()
	return &GeneratedReport{
		Content:     content,
		Format:      format,
		Filename:    filename,
		ContentType: format.ContentType(),
		Data:        data,
		Model:       result.Model,
		SourceCount: len(content.Sources),
	}, nil
}

func parseReportJSON(raw string) (SIAReportContent, error) {
	raw = strings.TrimSpace(raw)
	raw = strings.TrimPrefix(raw, "```json")
	raw = strings.TrimPrefix(raw, "```")
	raw = strings.TrimSuffix(raw, "```")
	raw = strings.TrimSpace(raw)

	var content SIAReportContent
	if err := json.Unmarshal([]byte(raw), &content); err != nil {
		return SIAReportContent{}, err
	}
	return content, nil
}

func normalizeReportContent(content *SIAReportContent) {
	content.Title = strings.TrimSpace(content.Title)
	content.Summary = strings.TrimSpace(content.Summary)
	if content.Title == "" {
		content.Title = "SIA Research Report"
	}
	if content.Summary == "" {
		content.Summary = "Research report generated by SIA (Smart Intelligence Assistant)."
	}

	for i := range content.Sections {
		content.Sections[i].Heading = strings.TrimSpace(content.Sections[i].Heading)
		content.Sections[i].Paragraphs = trimStrings(content.Sections[i].Paragraphs)
		content.Sections[i].Bullets = trimStrings(content.Sections[i].Bullets)
	}
	content.Recommendations = trimStrings(content.Recommendations)

	for i := range content.Tables {
		content.Tables[i].Title = strings.TrimSpace(content.Tables[i].Title)
		content.Tables[i].Headers = trimStrings(content.Tables[i].Headers)
		for j := range content.Tables[i].Rows {
			content.Tables[i].Rows[j] = trimStrings(content.Tables[i].Rows[j])
		}
	}

	for i := range content.Sources {
		content.Sources[i].Title = strings.TrimSpace(content.Sources[i].Title)
		content.Sources[i].URL = strings.TrimSpace(content.Sources[i].URL)
	}
}

func trimStrings(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value != "" {
			out = append(out, value)
		}
	}
	return out
}

func buildReportFile(content SIAReportContent, format ReportFormat) ([]byte, error) {
	switch format {
	case ReportFormatWord:
		return buildWordReport(content)
	case ReportFormatExcel:
		return buildExcelReport(content)
	case ReportFormatPowerPoint:
		return buildPowerPointReport(content)
	default:
		return nil, fmt.Errorf("unsupported format %q", format)
	}
}

// BuildReportFileForTest exposes report builders for unit tests.
func BuildReportFileForTest(content SIAReportContent, format ReportFormat) ([]byte, error) {
	var buf bytes.Buffer
	normalizeReportContent(&content)
	data, err := buildReportFile(content, format)
	if err != nil {
		return nil, err
	}
	buf.Write(data)
	return buf.Bytes(), nil
}
